version: '2'
services:
  db:
    restart: always
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: secret
        POSTGRES_USER: flask
        POSTGRES_DB: flask_db
    ports:
      - "54323:5432"
  web:
    build: .
    restart: always
    command: /usr/local/bin/gunicorn wsgi -w 2 -b :8000 --reload
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    restart: always
    build: ./nginx/.
    ports:
        - "80:80"
    volumes:
        - /www/static
    volumes_from:
        - web
    links:
        - web:web
volumes:
  postgres-data:
    driver: local
